source 'https://rubygems.org'

ruby '3.0.0'

gem 'bcrypt'
gem 'byebug'
gem 'capybara'
gem 'capybara-screenshot'
gem 'chilkat'
gem 'chunky_png', '1.3.7'
gem 'cucumber'
gem 'cucumber-api'
gem 'cuke_sniffer'
gem 'data_magic', '~> 0.21'
gem 'date'
gem 'dotenv'
gem 'dotiw'
gem 'google-api-client'
gem 'imatcher', '0.1.5'
gem 'jsonpath'
gem 'os'
gem 'parallel_tests'
gem 'pdf-reader', '~> 2.5.0'
gem 'pry'
gem 'pry-byebug'
gem 'rails_helper', '~> 2.2', '>= 2.2.2'
gem 'rake'
gem 'report_builder'
gem 'require_all'
gem 'rest-client'
gem 'roo'
gem 'roo-xls'
gem 'rspec'
gem 'rspec-expectations'
gem 'rspec-retry'
gem 'rubocop', '1.14.0', require: false
gem 'rubyXL', '~> 3.4', '>= 3.4.14'
gem 'selenium-webdriver'
gem 'show_me_the_cookies'
gem 'simple_xlsx_reader'
gem 'site_prism'
gem 'site_prism-table'
gem 'sorted_set'
gem 'syntax'
gem 'time_diff', '~> 0.3.0'
gem 'uuidtools'
gem 'webdrivers', '~> 3.0'
